exclude: |
    (?x)(
        src/ansys/aedt/toolkits/antennas/ui/antennas_main.py
    )

repos:

- repo: https://github.com/psf/black
  rev: 23.1.0  # IF VERSION CHANGES --> MODIFY "blacken-docs" MANUALLY AS WELL!!
  hooks:
  - id: black
    args:
      - --line-length=100

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      args: ['--force-single-line-imports', '--profile', 'black']

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args:
      - --max-line-length=100

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.2
  hooks:
  - id: codespell
    args: ["--ignore-words=ignore_words.txt"]

# - repo: https://github.com/python-jsonschema/check-jsonschema
#   rev: 0.21.0
#   hooks:
#     - id: check-github-workflows

# - repo: https://github.com/pycqa/pydocstyle
#   rev: 6.1.1
#   hooks:
#   - id: pydocstyle
#     additional_dependencies: [toml]
#     exclude: "tests/"

- repo: https://github.com/asottile/blacken-docs
  rev: 1.13.0
  hooks:
  -   id: blacken-docs
      additional_dependencies: [black==23.1.0]
