comment:
  layout: "diff"
  behavior: default
  require_changes: true  # Avoid coverage comment if no files are changed.

coverage:
  status:
    project: false
    patch:
      default:
        # basic
        target: 85%
        if_not_found: success
        if_ci_failed: error
        if_no_uploads: error

codecov:
  notify:
    wait_for_ci: yes
