name = "Vertical Trapezoidal Monopole"

[object_1]
name = "antenna_VerticalTrapezoidalMonopole"
color = [255, 128, 65]
opacity = 0.1

[object_2]
name = "ground_VerticalTrapezoidalMonopole"
color = [255, 128, 65]
opacity = 0.1

[object_3]
name = "port_lump_VerticalTrapezoidalMonopole"
color = [128, 0, 0]
opacity = 0.2
