name = "Gregorian"

[object_1]
name = "reflector"
color = [255, 128, 65]
opacity = 0.25

[object_2]
name = "subreflector"
color = [255, 128, 65]
opacity = 0.35

[object_3]
name = "feed"
color = [230, 230, 230]
opacity = 0.8

[object_4]
name = "port"
color = [128, 0, 0]
opacity = 0.2

[object_5]
name = "port_cap"
color = [132, 132, 192]
opacity = 0.8
