Name = "SeqRotated2Patch"
Frequency = 5.0
Substrate_Material = ["Teflon (tm)", "FR4_epoxy", "Rogers RT / duroid 6002(tm)"]
Substrate_Height = 1.272
Feed_Rotation_Angle = 45.0
Element_1_Rotation_Angle = 0.0
Element_2_Rotation_Angle = -90.0
Element_3_Rotation_Angle = -180.0
Element_4_Rotation_Angle = -270.0
Element_1_Port_Phase = 0.0
Element_2_Port_Phase = 90.0
Element_3_Port_Phase = 180.0
Element_4_Port_Phase = 270.0
Outer_Boundary = ["Radiation", "PML", "FEBI", "None"]
Origin_X_Position = 0.0
Origin_Y_Position = 0.0
Origin_Z_Position = 0.0
Coordinate_System = "Global"
