Name = "SplashPlate"
Frequency = 20.0
Feed_Type = ["CircularWG_Choke", "Pyramidal", "Conical", "Elliptical"]
Primary_Diameter = 308.0
Primary_Focal = 200.0
Sub_Diameter = 56.0
Sub_Focal = 20.0
Sub_Thickness = 1.0
Sub_Height = 1.0
Outer_Boundary = ["Radiation", "PML", "FEBI", "None"]
Origin_X_Position = 0.0
Origin_Y_Position = 0.0
Origin_Z_Position = 0.0
Coordinate_System = "Global"
