Name = "LogPeriodicArray"
Material = "pec"
Input_Resistance = 100.0
Load_Impedance = 118.7921
Boom_Spacing = 0.22693
Tau_Ratio = 0.9265
Sigma_Ratio = 0.198
Base_Element_Length = 32.98
Base_Element_Radius = 0.093165
Number_Of_Elements = 8
Outer_Boundary = ["Radiation", "PML", "FEBI", "None"]
Origin_X_Position = 0.0
Origin_Y_Position = 0.0
Origin_Z_Position = 0.0
Coordinate_System = "Global"
