[Bowtie]
models = ["BowTieNormal", "BowTieRounded", "BowTieSlot"]

[ConicalSpiral]
models = ["Archimedean", "Log", "Sinuous"]

[Custom]
models = ["GPSPatchCeramic"]

[Waveguide]
models = [
  "CircularWaveguide",
  "RectangularWaveguide",
  "RectangularWaveguideSlotArray",
]

[Dipole]
models = ["PlanarDipole", "WireDipole"]

[Helix]
models = ["AxialMode", "AxialModeTaper", "NormalMode", "QuadrifilarOpen", "QuadrifilarShort"]

[Horn]
models = [
  "Conical",
  "Corrugated",
  "EPlane",
  "Elliptical",
  "HPlane",
  "Pyramidal",
  "PyramidalRidged",
  "QuadRidged",
]

[LogPeriodic]
models = ["LogPeriodicArray", "LogPeriodicToothed", "LogPeriodicTrapezoidal"]

[Misc]
models = ["Bicone", "Discone"]

[Monopole]
models = [
  "BladeAntenna",
  "CircularDiscMonopole",
  "EllipticalBaseStripMonopole",
  "VerticalTrapezoidalMonopole",
  "WireMonopole",
]

[Patch]
models = [
  "EllipticalEdge",
  "EllipticalInset",
  "EllipticalProbe",
  "MbyNPatchArray",
  "RectangularPatchEdge",
  "RectangularPatchInset",
  "RectangularPatchProbe",
  "SeqRotated2Patch",
]

[PIFA]
models = ["PlanarInvertedF", "ShortingPin", "ShortingPlate"]

[PlanarSpiral]
models = [
  "PlanarArchimedean",
  "PlanarArchimedeanCavity",
  "PlanarLog",
  "PlanarLogCavity",
  "PlanarSinuous",
  "PlanarSinuousCavity",
]

[Reflector]
models = []

[Slot]
models = ["SlotCavityBackedArray", "SlotGap", "SlotMicrostrip", "SlotTBar"]

[Vivaldi]
models = ["Vivaldi", "VivaldiStepped"]

[YagiUda]
models = ["QuasiYagi", "WireYagiUda"]
