[Bowtie]
models = ["BowTieNormal", "BowTieRounded", "BowTieSlot"]

[ConicalSpiral]
models = ["Archimedean", "Log", "Sinuous"]

[Custom]
models = ["GPSPatchCeramic"]

[Dipole]
models = ["PlanarDipole", "WireDipole"]

[Helix]
models = ["AxialMode", "AxialModeTaper", "NormalMode", "QuadrifilarOpen", "QuadrifilarShort"]

[Horn]
models = ["Conical", "Corrugated",
    "EPlane", "Elliptical",
    "HPlane", "Pyramidal",
    "PyramidalRidged", "QuadRidged"]

[LogPeriodic]
models = []

[Misc]
models = ["Bicone", "Discone"]

[Monopole]
models = []

[Patch]
models = ["RectangularPatchEdge", "RectangularPatchInset",
    "RectangularPatchProbe"]

[PIFA]
models = []

[PlanarSpiral]
models = []

[Reflector]
models = []

[Slot]
models = []

[Vivaldi]
models = []

[YagiUda]
models = []
