Name = "Rectangular_Waveguide_Slot_Array"
Frequency = 10.3
Rectangular_Waveguide = ["WR-90", "WR-75", "WR-62"]
Material = ["pec", "copper", "aluminum"]
WG_Width = 22.86
WG_Height = 10.16
WG_Length = 278.335
Wall_Thickness = 1.27
Number_Of_Slots = 13
Inset_From_Feed = 9.4356
Inset_From_Termination = 28.3067
Slot_Spacing = 18.8711
Slot_Width = 1.5875
Slot_Length = 14.1393
Slot_Offset = 2.5646
Outer_Boundary = ["Radiation", "PML", "FEBI", "None"]
Origin_X_Position = 0.0
Origin_Y_Position = 0.0
Origin_Z_Position = 0.0
Coordinate_System = "Global"
