name = "Shorting Plate PIFA"

[object_1]
name = "sub_ShortingPlate"
color = [0, 128, 0]
opacity = 0.2

[object_2]
name = "gnd_ShortingPlate"
color = [255, 128, 65]
opacity = 0.9

[object_3]
name = "ant_ShortingPlate"
color = [255, 128, 65]
opacity = 0.9

[object_4]
name = "feed_pin_ShortingPlate"
color = [255, 128, 65]
opacity = 0.8

[object_5]
name = "feed_coax_ShortingPlate"
color = [255, 128, 65]
opacity = 0.8

[object_6]
name = "coax_ShortingPlate"
color = [128, 255, 255]
opacity = 0.8

[object_7]
name = "port_cap_ShortingPlate"
color = [132, 132, 193]
opacity = 0.8

[object_8]
name = "port_ShortingPlate"
color = [128, 0, 0]
opacity = 0.2

[object_9]
name = "shorting_plate_ShortingPlate"
color = [255, 128, 65]
opacity = 0.8
