name = "Circular Waveguide"

[object_1]
name = "metal"
color = [255, 128, 65]
opacity = 0.25

[object_2]
name = "port_cap"
color = [132, 132, 193]
opacity = 0.8

[object_3]
name = "port"
color = [128, 0, 0]
opacity = 0.2
