import os
import shutil
import sys

from cx_Freeze import Executable
from cx_Freeze import setup
import numpy

# General configuration
company_name = "Ansys Inc"
product_name = "Antenna Toolkit"

# Generate a random GUID
random_guid = "{70a724f2-2396-4264-94ce-5edff0d7fbc1}"

# Requisites and directories
build_dir = "build"
dist_dir = "dist"
exe_name = f"AntennaToolkit.exe"
icon_path = os.path.join("cx", "splash_icon.ico")
logo_path = os.path.join("cx", "antenna.png")
run_script = os.path.join("src", "ansys", "aedt", "toolkits", "antenna", "run_toolkit.py")
nsi_script = "setup.nsi"
license_file = "LICENSE"

# Create dist
os.makedirs(dist_dir, exist_ok=True)

# LICENSE verification
if not os.path.isfile(license_file):
    print(f"ERROR: LICENSE not found, required by: {nsi_script}")
    sys.exit(1)

# Packages
numpy_dir = os.path.dirname(numpy.__file__)
packages = [
    "pyaedt",
    "numpy",
    "pyedb",
    "matplotlib",
    "ansys.aedt.toolkits.common",
    "ansys.aedt.toolkits.antenna",
    "fileinput",
]

build_options = {
    "packages": packages,
    "includes": ["numpy", "numpy.f2py", "fileinput"],
    "excludes": ["tkinter*", "*sphinx*", "pyvista*", "vtk*", "sci*"],
    "include_msvcr": False,
    "include_files": [(numpy_dir, "lib/numpy"), icon_path, logo_path],
}

base = "Win32GUI" if sys.platform == "win32" else None

executables = [
    Executable(
        script=run_script,
        base=base,
        target_name=exe_name,
        icon=icon_path,
    )
]

# Build
setup(
    name=product_name,
    version="1",
    description="Ansys Antenna Toolkit",
    options={"build_exe": build_options},
    executables=executables,
)

# Post-build actions for Linux
# if sys.platform != "win32":
#     from glob import glob
#
#     print("Post-build: Copying cx_Freeze output to dist/ (Linux)")
#
#     # Look for the build output directory generated by cx_Freeze in Linux
#     build_exe_path = None
#     for path in glob(os.path.join(build_dir, "exe.*")):
#         if os.path.isdir(path):
#             build_exe_path = path
#             break
#
#     if build_exe_path:
#         # Clean up the dist directory before copying new files
#         shutil.rmtree(dist_dir, ignore_errors=True)
#         shutil.copytree(build_exe_path, dist_dir)
#         print(f"Copied build output to: {dist_dir}")
#     else:
#         print("ERROR: cx_Freeze output not found.")
#         sys.exit(1)
