name = "Microstrip Fed Slot"

[object_1]
name = "sub_slot"
color = [0, 128, 0]
opacity = 0.2

[object_2]
name = "gnd_slot"
color = [255, 128, 65]
opacity = 0.9

[object_3]
name = "feed_slot"
color = [255, 128, 65]
opacity = 0.9

[object_4]
name = "port_slot"
color = [128, 0, 0]
opacity = 0.4
